import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { notoSans } from "@repo/ui/config/fonts";


export const metadata: Metadata = {
  title: "Marketing website",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} antialiased`}>{children}</body>
    </html>
  );
}
