import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { notoSans } from "@repo/ui/config";
import { Toaster } from "@repo/ui/components/ui/toaster";


export const metadata: Metadata = {
  title: {
    template: '%s | Marketing website',
    default: 'Marketing website'
  },
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
