import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { notoSans } from "@repo/ui/config";
import AppProvider from "./app-provider";


export const metadata: Metadata = {
  title: {
    template: '%s | E-commerce website',
    default: 'E-commerce website'
  },
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      <body className={`${notoSans.className} antialiased`}>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
