name: Build UI and Deploy storybook to Chromatic

on:
  push:
    branches: [main]
    paths:
      - "apps/docs/**"
      - "packages/ui/**"
  pull_request:
    branches: [main]
    paths:
      - "apps/docs/**"
      - "packages/ui/**"

jobs:
  build-and-chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build UI styles
        run: npm run build:styles --workspace=packages/ui

      - name: Build UI components
        run: npm run build:components --workspace=packages/ui

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: apps/docs
